### ISSUE TITLE
Docs show optionals as required

### ISSUE THREAD

**Issue by lalalune** [RaccoonResearch/Simian#44]
<img width="985" alt="Screenshot 2024-05-06 at 11 26 21 PM" src="https://github.com/RaccoonResearch/Simian/assets/18633264/71227de2-8a58-4510-9c8e-faa6c4357825">

**Comment by AqeelAqeel** [comment]
docs/batch_rendering.md 
<img width="610" alt="Screenshot 2024-05-11 at 10 47 05 PM" src="https://github.com/RaccoonResearch/Simian/assets/12155302/c6871b98-93ac-41c6-937c-8857ef9214be">

arguments / docstring is where we're _supposed_ to read this in for MKDocs. might be reading it in incorectly. 

Will keep looking / reviewing MK Docs more

**Comment by lalalune** [comment]
https://github.com/mkdocstrings/griffe/issues/165

Seems like we need to structure it like this

class Example(NamedTuple):
    """A simple example of the autorefs bug

    Parameters
    ----------
    required : int
        A required value
    optional : float, optional
        An optional value, default is -3.6
    """

**Comment by pawamoy** [comment]
In the screenshot above, it looks like you're using the Google-style for docstrings. Just removes the dashes in front of parameter names and it should work as expected.

**Comment by lalalune** [comment]
> In the screenshot above, it looks like you're using the Google-style for docstrings. Just remove the dashes in front of parameter names and it should work as expected.
> 
> Otherwise, yes, you can also switch to the Numpydoc-style if this is what you prefer :)

Thank you, very useful
