### ISSUE TITLE
Simplify cmd line args

### ISSUE THREAD

**Issue by eric-prog** [RaccoonResearch/Simian#57]
This type of cmd: 

Command is too long and non-ideal. I wouldn't type this tbh and easy to forget:

/Applications/Blender.app/Contents/MacOS/Blender --background --python simian/render.py -- --output_dir "/Users/ericsheen/Desktop/Raccoon_Research/Simian/simian/render1"

**Comment by lalalune** [comment]
We will do a CLI tool so that people can just run `simian`. If you wanna go nuts on it we can even make a snap or pipx installer. But I don't think we should worry about this for now, mainly these have sane defaults so you don't need to run them

**Comment by eric-prog** [comment]
Ok sounds good!
