### ISSUE TITLE
Object scale size caption

### ISSUE THREAD

**Issue by lalalune** [RaccoonResearch/Simian#64]
Objects can be large, small, etc. We have the data for this in object_data.json

This should already be in place but doesn't seem to be in the captions.

We want to make sure this is applied to the objects in the scene.

1. Roll a scale between min and max
2. Pick the size type that is relevant
3. Choose one of the random descriptions
4. Add to the caption

**Comment by eric-prog** [comment]
https://github.com/RaccoonResearch/Simian/pull/86
